[package]
name = "cubalt"
version = "0.1.0"
authors = ["Soham Chowdhury <eoxcross@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simdeez = "1.0.0"
